# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainWwfMjTK.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1017, 564)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(670, 280, 151, 61))
        font = QFont()
        font.setFamily(u"Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setAutoDefault(False)
        self.graphicsView = QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setGeometry(QRect(330, 30, 322, 322))
        sizePolicy = QSizePolicy(QSizePolicy.Ignored, QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView_2 = QGraphicsView(self.centralwidget)
        self.graphicsView_2.setObjectName(u"graphicsView_2")
        self.graphicsView_2.setGeometry(QRect(0, 30, 322, 322))
        sizePolicy.setHeightForWidth(self.graphicsView_2.sizePolicy().hasHeightForWidth())
        self.graphicsView_2.setSizePolicy(sizePolicy)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(100, 0, 131, 31))
        font1 = QFont()
        font1.setFamily(u"Arial")
        font1.setPointSize(18)
        font1.setBold(True)
        font1.setWeight(75)
        self.label_5.setFont(font1)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(430, 0, 131, 31))
        self.label_6.setFont(font1)
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(330, 360, 321, 161))
        self.tabWidget.setElideMode(Qt.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.formLayoutWidget = QWidget(self.tab)
        self.formLayoutWidget.setObjectName(u"formLayoutWidget")
        self.formLayoutWidget.setGeometry(QRect(0, 0, 290, 131))
        self.formLayout = QFormLayout(self.formLayoutWidget)
        self.formLayout.setObjectName(u"formLayout")
        self.formLayout.setHorizontalSpacing(40)
        self.formLayout.setVerticalSpacing(15)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.radioButton = QRadioButton(self.formLayoutWidget)
        self.radioButton.setObjectName(u"radioButton")
        font2 = QFont()
        font2.setFamily(u"Arial")
        font2.setPointSize(14)
        font2.setBold(True)
        font2.setWeight(75)
        self.radioButton.setFont(font2)
        self.radioButton.setCheckable(True)
        self.radioButton.setChecked(False)
        self.radioButton.setAutoExclusive(True)

        self.formLayout.setWidget(0, QFormLayout.LabelRole, self.radioButton)

        self.radioButton_2 = QRadioButton(self.formLayoutWidget)
        self.radioButton_2.setObjectName(u"radioButton_2")
        self.radioButton_2.setFont(font2)
        self.radioButton_2.setCheckable(True)
        self.radioButton_2.setChecked(False)
        self.radioButton_2.setAutoExclusive(True)

        self.formLayout.setWidget(0, QFormLayout.FieldRole, self.radioButton_2)

        self.radioButton_3 = QRadioButton(self.formLayoutWidget)
        self.radioButton_3.setObjectName(u"radioButton_3")
        self.radioButton_3.setFont(font2)
        self.radioButton_3.setCheckable(True)
        self.radioButton_3.setChecked(True)
        self.radioButton_3.setAutoExclusive(True)

        self.formLayout.setWidget(1, QFormLayout.LabelRole, self.radioButton_3)

        self.radioButton_4 = QRadioButton(self.formLayoutWidget)
        self.radioButton_4.setObjectName(u"radioButton_4")
        self.radioButton_4.setFont(font2)
        self.radioButton_4.setCheckable(True)
        self.radioButton_4.setChecked(False)
        self.radioButton_4.setAutoExclusive(True)

        self.formLayout.setWidget(1, QFormLayout.FieldRole, self.radioButton_4)

        self.radioButton_9 = QRadioButton(self.formLayoutWidget)
        self.radioButton_9.setObjectName(u"radioButton_9")
        self.radioButton_9.setFont(font2)
        self.radioButton_9.setCheckable(True)
        self.radioButton_9.setChecked(False)
        self.radioButton_9.setAutoExclusive(True)

        self.formLayout.setWidget(2, QFormLayout.LabelRole, self.radioButton_9)

        self.radioButton_10 = QRadioButton(self.formLayoutWidget)
        self.radioButton_10.setObjectName(u"radioButton_10")
        self.radioButton_10.setFont(font2)
        self.radioButton_10.setCheckable(True)
        self.radioButton_10.setChecked(False)
        self.radioButton_10.setAutoExclusive(True)

        self.formLayout.setWidget(2, QFormLayout.FieldRole, self.radioButton_10)

        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.dial = QDial(self.tab_2)
        self.dial.setObjectName(u"dial")
        self.dial.setGeometry(QRect(170, 0, 80, 71))
        self.dial.setMaximum(255)
        self.dial.setValue(30)
        self.dial.setWrapping(False)
        self.dial.setNotchTarget(1.000000000000000)
        self.dial.setNotchesVisible(False)
        self.label_7 = QLabel(self.tab_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(190, 80, 110, 16))
        self.plainTextEdit = QPlainTextEdit(self.tab_2)
        self.plainTextEdit.setObjectName(u"plainTextEdit")
        self.plainTextEdit.setGeometry(QRect(240, 20, 40, 30))
        font3 = QFont()
        font3.setFamily(u"Arial")
        font3.setPointSize(11)
        font3.setBold(True)
        font3.setWeight(75)
        self.plainTextEdit.setFont(font3)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setCenterOnScroll(False)
        self.plainTextEdit_2 = QPlainTextEdit(self.tab_2)
        self.plainTextEdit_2.setObjectName(u"plainTextEdit_2")
        self.plainTextEdit_2.setGeometry(QRect(90, 20, 40, 30))
        self.plainTextEdit_2.setFont(font3)
        self.plainTextEdit_2.setReadOnly(True)
        self.plainTextEdit_2.setCenterOnScroll(False)
        self.dial_2 = QDial(self.tab_2)
        self.dial_2.setObjectName(u"dial_2")
        self.dial_2.setGeometry(QRect(20, 0, 80, 71))
        self.dial_2.setMinimum(1)
        self.dial_2.setMaximum(17)
        self.dial_2.setSingleStep(2)
        self.dial_2.setPageStep(2)
        self.dial_2.setValue(1)
        self.dial_2.setInvertedAppearance(False)
        self.dial_2.setWrapping(False)
        self.dial_2.setNotchTarget(1.000000000000000)
        self.dial_2.setNotchesVisible(False)
        self.label_8 = QLabel(self.tab_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(30, 80, 91, 16))
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.label_9 = QLabel(self.tab_5)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(0, 100, 80, 16))
        self.dial_3 = QDial(self.tab_5)
        self.dial_3.setObjectName(u"dial_3")
        self.dial_3.setGeometry(QRect(0, 0, 80, 71))
        self.dial_3.setMinimum(1)
        self.dial_3.setMaximum(100)
        self.dial_3.setSingleStep(1)
        self.dial_3.setPageStep(5)
        self.dial_3.setValue(1)
        self.dial_3.setInvertedAppearance(False)
        self.dial_3.setWrapping(False)
        self.dial_3.setNotchTarget(1.000000000000000)
        self.dial_3.setNotchesVisible(False)
        self.plainTextEdit_3 = QPlainTextEdit(self.tab_5)
        self.plainTextEdit_3.setObjectName(u"plainTextEdit_3")
        self.plainTextEdit_3.setGeometry(QRect(20, 70, 40, 30))
        self.plainTextEdit_3.setFont(font3)
        self.plainTextEdit_3.setReadOnly(True)
        self.plainTextEdit_3.setCenterOnScroll(False)
        self.label_10 = QLabel(self.tab_5)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(80, 100, 80, 16))
        self.dial_4 = QDial(self.tab_5)
        self.dial_4.setObjectName(u"dial_4")
        self.dial_4.setGeometry(QRect(80, 0, 80, 71))
        self.dial_4.setMinimum(1)
        self.dial_4.setMaximum(100)
        self.dial_4.setSingleStep(1)
        self.dial_4.setPageStep(5)
        self.dial_4.setValue(1)
        self.dial_4.setInvertedAppearance(False)
        self.dial_4.setWrapping(False)
        self.dial_4.setNotchTarget(1.000000000000000)
        self.dial_4.setNotchesVisible(False)
        self.plainTextEdit_4 = QPlainTextEdit(self.tab_5)
        self.plainTextEdit_4.setObjectName(u"plainTextEdit_4")
        self.plainTextEdit_4.setGeometry(QRect(100, 70, 40, 30))
        self.plainTextEdit_4.setFont(font3)
        self.plainTextEdit_4.setReadOnly(True)
        self.plainTextEdit_4.setCenterOnScroll(False)
        self.label_11 = QLabel(self.tab_5)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(170, 100, 60, 16))
        self.dial_5 = QDial(self.tab_5)
        self.dial_5.setObjectName(u"dial_5")
        self.dial_5.setGeometry(QRect(160, 0, 80, 71))
        self.dial_5.setMinimum(1)
        self.dial_5.setMaximum(100)
        self.dial_5.setSingleStep(1)
        self.dial_5.setPageStep(1)
        self.dial_5.setValue(1)
        self.dial_5.setInvertedAppearance(False)
        self.dial_5.setWrapping(False)
        self.dial_5.setNotchTarget(1.000000000000000)
        self.dial_5.setNotchesVisible(False)
        self.plainTextEdit_5 = QPlainTextEdit(self.tab_5)
        self.plainTextEdit_5.setObjectName(u"plainTextEdit_5")
        self.plainTextEdit_5.setGeometry(QRect(180, 70, 40, 30))
        self.plainTextEdit_5.setFont(font3)
        self.plainTextEdit_5.setReadOnly(True)
        self.plainTextEdit_5.setCenterOnScroll(False)
        self.label_12 = QLabel(self.tab_5)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(240, 100, 80, 16))
        self.dial_6 = QDial(self.tab_5)
        self.dial_6.setObjectName(u"dial_6")
        self.dial_6.setGeometry(QRect(240, 0, 80, 71))
        self.dial_6.setMinimum(1)
        self.dial_6.setMaximum(100)
        self.dial_6.setSingleStep(1)
        self.dial_6.setPageStep(1)
        self.dial_6.setValue(1)
        self.dial_6.setInvertedAppearance(False)
        self.dial_6.setWrapping(False)
        self.dial_6.setNotchTarget(1.000000000000000)
        self.dial_6.setNotchesVisible(False)
        self.plainTextEdit_6 = QPlainTextEdit(self.tab_5)
        self.plainTextEdit_6.setObjectName(u"plainTextEdit_6")
        self.plainTextEdit_6.setGeometry(QRect(260, 70, 40, 30))
        self.plainTextEdit_6.setFont(font3)
        self.plainTextEdit_6.setReadOnly(True)
        self.plainTextEdit_6.setCenterOnScroll(False)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.plainTextEdit_10 = QPlainTextEdit(self.tab_6)
        self.plainTextEdit_10.setObjectName(u"plainTextEdit_10")
        self.plainTextEdit_10.setGeometry(QRect(260, 70, 40, 30))
        self.plainTextEdit_10.setFont(font3)
        self.plainTextEdit_10.setReadOnly(True)
        self.plainTextEdit_10.setCenterOnScroll(False)
        self.dial_9 = QDial(self.tab_6)
        self.dial_9.setObjectName(u"dial_9")
        self.dial_9.setGeometry(QRect(0, 0, 80, 71))
        self.dial_9.setMinimum(1)
        self.dial_9.setMaximum(800)
        self.dial_9.setSingleStep(1)
        self.dial_9.setPageStep(10)
        self.dial_9.setValue(800)
        self.dial_9.setInvertedAppearance(False)
        self.dial_9.setWrapping(False)
        self.dial_9.setNotchTarget(1.000000000000000)
        self.dial_9.setNotchesVisible(False)
        self.dial_7 = QDial(self.tab_6)
        self.dial_7.setObjectName(u"dial_7")
        self.dial_7.setGeometry(QRect(80, 0, 80, 71))
        self.dial_7.setMinimum(1)
        self.dial_7.setMaximum(800)
        self.dial_7.setSingleStep(1)
        self.dial_7.setPageStep(10)
        self.dial_7.setValue(800)
        self.dial_7.setInvertedAppearance(False)
        self.dial_7.setWrapping(False)
        self.dial_7.setNotchTarget(1.000000000000000)
        self.dial_7.setNotchesVisible(False)
        self.plainTextEdit_7 = QPlainTextEdit(self.tab_6)
        self.plainTextEdit_7.setObjectName(u"plainTextEdit_7")
        self.plainTextEdit_7.setGeometry(QRect(100, 70, 40, 30))
        self.plainTextEdit_7.setFont(font3)
        self.plainTextEdit_7.setReadOnly(True)
        self.plainTextEdit_7.setCenterOnScroll(False)
        self.label_16 = QLabel(self.tab_6)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(80, 100, 80, 16))
        self.plainTextEdit_8 = QPlainTextEdit(self.tab_6)
        self.plainTextEdit_8.setObjectName(u"plainTextEdit_8")
        self.plainTextEdit_8.setGeometry(QRect(20, 70, 40, 30))
        self.plainTextEdit_8.setFont(font3)
        self.plainTextEdit_8.setReadOnly(True)
        self.plainTextEdit_8.setCenterOnScroll(False)
        self.label_13 = QLabel(self.tab_6)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(170, 100, 60, 16))
        self.label_15 = QLabel(self.tab_6)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(0, 100, 80, 16))
        self.dial_10 = QDial(self.tab_6)
        self.dial_10.setObjectName(u"dial_10")
        self.dial_10.setGeometry(QRect(160, 0, 80, 71))
        self.dial_10.setMinimum(1)
        self.dial_10.setMaximum(800)
        self.dial_10.setSingleStep(1)
        self.dial_10.setPageStep(10)
        self.dial_10.setValue(800)
        self.dial_10.setInvertedAppearance(False)
        self.dial_10.setWrapping(False)
        self.dial_10.setNotchTarget(1.000000000000000)
        self.dial_10.setNotchesVisible(False)
        self.plainTextEdit_9 = QPlainTextEdit(self.tab_6)
        self.plainTextEdit_9.setObjectName(u"plainTextEdit_9")
        self.plainTextEdit_9.setGeometry(QRect(180, 70, 40, 30))
        self.plainTextEdit_9.setFont(font3)
        self.plainTextEdit_9.setReadOnly(True)
        self.plainTextEdit_9.setCenterOnScroll(False)
        self.dial_8 = QDial(self.tab_6)
        self.dial_8.setObjectName(u"dial_8")
        self.dial_8.setGeometry(QRect(240, 0, 80, 71))
        self.dial_8.setMinimum(1)
        self.dial_8.setMaximum(800)
        self.dial_8.setSingleStep(1)
        self.dial_8.setPageStep(10)
        self.dial_8.setValue(800)
        self.dial_8.setInvertedAppearance(False)
        self.dial_8.setWrapping(False)
        self.dial_8.setNotchTarget(1.000000000000000)
        self.dial_8.setNotchesVisible(False)
        self.label_14 = QLabel(self.tab_6)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(240, 100, 80, 16))
        self.tabWidget.addTab(self.tab_6, "")
        self.tabWidget_2 = QTabWidget(self.centralwidget)
        self.tabWidget_2.setObjectName(u"tabWidget_2")
        self.tabWidget_2.setGeometry(QRect(0, 360, 321, 161))
        self.tabWidget_2.setElideMode(Qt.ElideNone)
        self.tabWidget_2.setDocumentMode(False)
        self.tabWidget_2.setTabsClosable(False)
        self.tabWidget_2.setMovable(False)
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.formLayoutWidget_2 = QWidget(self.tab_3)
        self.formLayoutWidget_2.setObjectName(u"formLayoutWidget_2")
        self.formLayoutWidget_2.setGeometry(QRect(0, 0, 290, 131))
        self.formLayout_2 = QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setObjectName(u"formLayout_2")
        self.formLayout_2.setHorizontalSpacing(40)
        self.formLayout_2.setVerticalSpacing(15)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.radioButton_5 = QRadioButton(self.formLayoutWidget_2)
        self.radioButton_5.setObjectName(u"radioButton_5")
        self.radioButton_5.setFont(font2)
        self.radioButton_5.setCheckable(True)
        self.radioButton_5.setChecked(False)
        self.radioButton_5.setAutoExclusive(True)

        self.formLayout_2.setWidget(0, QFormLayout.LabelRole, self.radioButton_5)

        self.radioButton_6 = QRadioButton(self.formLayoutWidget_2)
        self.radioButton_6.setObjectName(u"radioButton_6")
        self.radioButton_6.setFont(font2)
        self.radioButton_6.setCheckable(True)
        self.radioButton_6.setChecked(False)
        self.radioButton_6.setAutoExclusive(True)

        self.formLayout_2.setWidget(0, QFormLayout.FieldRole, self.radioButton_6)

        self.radioButton_7 = QRadioButton(self.formLayoutWidget_2)
        self.radioButton_7.setObjectName(u"radioButton_7")
        self.radioButton_7.setFont(font2)
        self.radioButton_7.setCheckable(True)
        self.radioButton_7.setChecked(True)
        self.radioButton_7.setAutoExclusive(True)

        self.formLayout_2.setWidget(1, QFormLayout.LabelRole, self.radioButton_7)

        self.radioButton_8 = QRadioButton(self.formLayoutWidget_2)
        self.radioButton_8.setObjectName(u"radioButton_8")
        self.radioButton_8.setFont(font2)
        self.radioButton_8.setCheckable(True)
        self.radioButton_8.setChecked(False)
        self.radioButton_8.setAutoExclusive(True)

        self.formLayout_2.setWidget(1, QFormLayout.FieldRole, self.radioButton_8)

        self.radioButton_11 = QRadioButton(self.formLayoutWidget_2)
        self.radioButton_11.setObjectName(u"radioButton_11")
        self.radioButton_11.setFont(font2)
        self.radioButton_11.setCheckable(True)
        self.radioButton_11.setChecked(False)
        self.radioButton_11.setAutoExclusive(True)

        self.formLayout_2.setWidget(2, QFormLayout.LabelRole, self.radioButton_11)

        self.radioButton_12 = QRadioButton(self.formLayoutWidget_2)
        self.radioButton_12.setObjectName(u"radioButton_12")
        self.radioButton_12.setFont(font2)
        self.radioButton_12.setCheckable(True)
        self.radioButton_12.setChecked(False)
        self.radioButton_12.setAutoExclusive(True)

        self.formLayout_2.setWidget(2, QFormLayout.FieldRole, self.radioButton_12)

        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.dial_11 = QDial(self.tab_4)
        self.dial_11.setObjectName(u"dial_11")
        self.dial_11.setGeometry(QRect(170, 0, 80, 71))
        self.dial_11.setMaximum(255)
        self.dial_11.setValue(30)
        self.dial_11.setWrapping(False)
        self.dial_11.setNotchTarget(1.000000000000000)
        self.dial_11.setNotchesVisible(False)
        self.label_17 = QLabel(self.tab_4)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(190, 80, 110, 16))
        self.plainTextEdit_11 = QPlainTextEdit(self.tab_4)
        self.plainTextEdit_11.setObjectName(u"plainTextEdit_11")
        self.plainTextEdit_11.setGeometry(QRect(240, 20, 40, 30))
        self.plainTextEdit_11.setFont(font3)
        self.plainTextEdit_11.setReadOnly(True)
        self.plainTextEdit_11.setCenterOnScroll(False)
        self.plainTextEdit_12 = QPlainTextEdit(self.tab_4)
        self.plainTextEdit_12.setObjectName(u"plainTextEdit_12")
        self.plainTextEdit_12.setGeometry(QRect(90, 20, 40, 30))
        self.plainTextEdit_12.setFont(font3)
        self.plainTextEdit_12.setReadOnly(True)
        self.plainTextEdit_12.setCenterOnScroll(False)
        self.dial_12 = QDial(self.tab_4)
        self.dial_12.setObjectName(u"dial_12")
        self.dial_12.setGeometry(QRect(20, 0, 80, 71))
        self.dial_12.setMinimum(1)
        self.dial_12.setMaximum(17)
        self.dial_12.setSingleStep(2)
        self.dial_12.setPageStep(2)
        self.dial_12.setValue(1)
        self.dial_12.setInvertedAppearance(False)
        self.dial_12.setWrapping(False)
        self.dial_12.setNotchTarget(1.000000000000000)
        self.dial_12.setNotchesVisible(False)
        self.label_18 = QLabel(self.tab_4)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(50, 80, 91, 16))
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_7 = QWidget()
        self.tab_7.setObjectName(u"tab_7")
        self.label_19 = QLabel(self.tab_7)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(0, 100, 80, 16))
        self.dial_13 = QDial(self.tab_7)
        self.dial_13.setObjectName(u"dial_13")
        self.dial_13.setGeometry(QRect(0, 0, 80, 71))
        self.dial_13.setMinimum(1)
        self.dial_13.setMaximum(100)
        self.dial_13.setSingleStep(1)
        self.dial_13.setPageStep(5)
        self.dial_13.setValue(1)
        self.dial_13.setInvertedAppearance(False)
        self.dial_13.setWrapping(False)
        self.dial_13.setNotchTarget(1.000000000000000)
        self.dial_13.setNotchesVisible(False)
        self.plainTextEdit_13 = QPlainTextEdit(self.tab_7)
        self.plainTextEdit_13.setObjectName(u"plainTextEdit_13")
        self.plainTextEdit_13.setGeometry(QRect(20, 70, 40, 30))
        self.plainTextEdit_13.setFont(font3)
        self.plainTextEdit_13.setReadOnly(True)
        self.plainTextEdit_13.setCenterOnScroll(False)
        self.label_20 = QLabel(self.tab_7)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(80, 100, 80, 16))
        self.dial_14 = QDial(self.tab_7)
        self.dial_14.setObjectName(u"dial_14")
        self.dial_14.setGeometry(QRect(80, 0, 80, 71))
        self.dial_14.setMinimum(1)
        self.dial_14.setMaximum(100)
        self.dial_14.setSingleStep(1)
        self.dial_14.setPageStep(5)
        self.dial_14.setValue(1)
        self.dial_14.setInvertedAppearance(False)
        self.dial_14.setWrapping(False)
        self.dial_14.setNotchTarget(1.000000000000000)
        self.dial_14.setNotchesVisible(False)
        self.plainTextEdit_14 = QPlainTextEdit(self.tab_7)
        self.plainTextEdit_14.setObjectName(u"plainTextEdit_14")
        self.plainTextEdit_14.setGeometry(QRect(100, 70, 40, 30))
        self.plainTextEdit_14.setFont(font3)
        self.plainTextEdit_14.setReadOnly(True)
        self.plainTextEdit_14.setCenterOnScroll(False)
        self.label_21 = QLabel(self.tab_7)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(170, 100, 60, 16))
        self.dial_15 = QDial(self.tab_7)
        self.dial_15.setObjectName(u"dial_15")
        self.dial_15.setGeometry(QRect(160, 0, 80, 71))
        self.dial_15.setMinimum(1)
        self.dial_15.setMaximum(100)
        self.dial_15.setSingleStep(1)
        self.dial_15.setPageStep(1)
        self.dial_15.setValue(1)
        self.dial_15.setInvertedAppearance(False)
        self.dial_15.setWrapping(False)
        self.dial_15.setNotchTarget(1.000000000000000)
        self.dial_15.setNotchesVisible(False)
        self.plainTextEdit_15 = QPlainTextEdit(self.tab_7)
        self.plainTextEdit_15.setObjectName(u"plainTextEdit_15")
        self.plainTextEdit_15.setGeometry(QRect(180, 70, 40, 30))
        self.plainTextEdit_15.setFont(font3)
        self.plainTextEdit_15.setReadOnly(True)
        self.plainTextEdit_15.setCenterOnScroll(False)
        self.label_22 = QLabel(self.tab_7)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(240, 100, 80, 16))
        self.dial_16 = QDial(self.tab_7)
        self.dial_16.setObjectName(u"dial_16")
        self.dial_16.setGeometry(QRect(240, 0, 80, 71))
        self.dial_16.setMinimum(1)
        self.dial_16.setMaximum(100)
        self.dial_16.setSingleStep(1)
        self.dial_16.setPageStep(1)
        self.dial_16.setValue(1)
        self.dial_16.setInvertedAppearance(False)
        self.dial_16.setWrapping(False)
        self.dial_16.setNotchTarget(1.000000000000000)
        self.dial_16.setNotchesVisible(False)
        self.plainTextEdit_16 = QPlainTextEdit(self.tab_7)
        self.plainTextEdit_16.setObjectName(u"plainTextEdit_16")
        self.plainTextEdit_16.setGeometry(QRect(260, 70, 40, 30))
        self.plainTextEdit_16.setFont(font3)
        self.plainTextEdit_16.setReadOnly(True)
        self.plainTextEdit_16.setCenterOnScroll(False)
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tab_8 = QWidget()
        self.tab_8.setObjectName(u"tab_8")
        self.plainTextEdit_17 = QPlainTextEdit(self.tab_8)
        self.plainTextEdit_17.setObjectName(u"plainTextEdit_17")
        self.plainTextEdit_17.setGeometry(QRect(260, 70, 40, 30))
        self.plainTextEdit_17.setFont(font3)
        self.plainTextEdit_17.setReadOnly(True)
        self.plainTextEdit_17.setCenterOnScroll(False)
        self.dial_17 = QDial(self.tab_8)
        self.dial_17.setObjectName(u"dial_17")
        self.dial_17.setGeometry(QRect(0, 0, 80, 71))
        self.dial_17.setMinimum(1)
        self.dial_17.setMaximum(800)
        self.dial_17.setSingleStep(1)
        self.dial_17.setPageStep(10)
        self.dial_17.setValue(800)
        self.dial_17.setInvertedAppearance(False)
        self.dial_17.setWrapping(False)
        self.dial_17.setNotchTarget(1.000000000000000)
        self.dial_17.setNotchesVisible(False)
        self.dial_18 = QDial(self.tab_8)
        self.dial_18.setObjectName(u"dial_18")
        self.dial_18.setGeometry(QRect(80, 0, 80, 71))
        self.dial_18.setMinimum(1)
        self.dial_18.setMaximum(800)
        self.dial_18.setSingleStep(1)
        self.dial_18.setPageStep(10)
        self.dial_18.setValue(800)
        self.dial_18.setInvertedAppearance(False)
        self.dial_18.setWrapping(False)
        self.dial_18.setNotchTarget(1.000000000000000)
        self.dial_18.setNotchesVisible(False)
        self.plainTextEdit_18 = QPlainTextEdit(self.tab_8)
        self.plainTextEdit_18.setObjectName(u"plainTextEdit_18")
        self.plainTextEdit_18.setGeometry(QRect(100, 70, 40, 30))
        self.plainTextEdit_18.setFont(font3)
        self.plainTextEdit_18.setReadOnly(True)
        self.plainTextEdit_18.setCenterOnScroll(False)
        self.label_23 = QLabel(self.tab_8)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(80, 100, 80, 16))
        self.plainTextEdit_19 = QPlainTextEdit(self.tab_8)
        self.plainTextEdit_19.setObjectName(u"plainTextEdit_19")
        self.plainTextEdit_19.setGeometry(QRect(20, 70, 40, 30))
        self.plainTextEdit_19.setFont(font3)
        self.plainTextEdit_19.setReadOnly(True)
        self.plainTextEdit_19.setCenterOnScroll(False)
        self.label_24 = QLabel(self.tab_8)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(170, 100, 60, 16))
        self.label_25 = QLabel(self.tab_8)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(0, 100, 80, 16))
        self.dial_19 = QDial(self.tab_8)
        self.dial_19.setObjectName(u"dial_19")
        self.dial_19.setGeometry(QRect(160, 0, 80, 71))
        self.dial_19.setMinimum(1)
        self.dial_19.setMaximum(800)
        self.dial_19.setSingleStep(1)
        self.dial_19.setPageStep(10)
        self.dial_19.setValue(800)
        self.dial_19.setInvertedAppearance(False)
        self.dial_19.setWrapping(False)
        self.dial_19.setNotchTarget(1.000000000000000)
        self.dial_19.setNotchesVisible(False)
        self.plainTextEdit_20 = QPlainTextEdit(self.tab_8)
        self.plainTextEdit_20.setObjectName(u"plainTextEdit_20")
        self.plainTextEdit_20.setGeometry(QRect(180, 70, 40, 30))
        self.plainTextEdit_20.setFont(font3)
        self.plainTextEdit_20.setReadOnly(True)
        self.plainTextEdit_20.setCenterOnScroll(False)
        self.dial_20 = QDial(self.tab_8)
        self.dial_20.setObjectName(u"dial_20")
        self.dial_20.setGeometry(QRect(240, 0, 80, 71))
        self.dial_20.setMinimum(1)
        self.dial_20.setMaximum(800)
        self.dial_20.setSingleStep(1)
        self.dial_20.setPageStep(10)
        self.dial_20.setValue(800)
        self.dial_20.setInvertedAppearance(False)
        self.dial_20.setWrapping(False)
        self.dial_20.setNotchTarget(1.000000000000000)
        self.dial_20.setNotchesVisible(False)
        self.label_26 = QLabel(self.tab_8)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(240, 100, 80, 16))
        self.tabWidget_2.addTab(self.tab_8, "")
        self.layoutWidget = QWidget(self.centralwidget)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(660, 90, 361, 121))
        self.gridLayout = QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.lcdNumber = QLCDNumber(self.layoutWidget)
        self.lcdNumber.setObjectName(u"lcdNumber")
        font4 = QFont()
        font4.setFamily(u"Arial")
        font4.setPointSize(9)
        font4.setBold(True)
        font4.setWeight(75)
        self.lcdNumber.setFont(font4)
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setDigitCount(5)
        self.lcdNumber.setSegmentStyle(QLCDNumber.Flat)
        self.lcdNumber.setProperty("value", 123.000000000000000)
        self.lcdNumber.setProperty("intValue", 123)

        self.gridLayout.addWidget(self.lcdNumber, 0, 1, 1, 1)

        self.label = QLabel(self.layoutWidget)
        self.label.setObjectName(u"label")
        font5 = QFont()
        font5.setFamily(u"Arial")
        font5.setPointSize(22)
        self.label.setFont(font5)

        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.lcdNumber_2 = QLCDNumber(self.layoutWidget)
        self.lcdNumber_2.setObjectName(u"lcdNumber_2")
        self.lcdNumber_2.setFrameShadow(QFrame.Sunken)
        self.lcdNumber_2.setLineWidth(1)
        self.lcdNumber_2.setSegmentStyle(QLCDNumber.Flat)

        self.gridLayout.addWidget(self.lcdNumber_2, 1, 1, 1, 1)

        self.label_2 = QLabel(self.layoutWidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setEnabled(True)
        self.label_2.setFont(font5)
        self.label_2.setFrameShadow(QFrame.Plain)

        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)

        self.label_3 = QLabel(self.layoutWidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setFont(font5)

        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)

        self.label_4 = QLabel(self.layoutWidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setEnabled(True)
        self.label_4.setFont(font5)

        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)

        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(840, 280, 151, 61))
        self.pushButton_2.setFont(font)
        self.pushButton_2.setAutoDefault(False)
        self.label_27 = QLabel(self.centralwidget)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(700, 220, 251, 51))
        font6 = QFont()
        font6.setFamily(u"Arial")
        font6.setPointSize(12)
        font6.setBold(True)
        font6.setWeight(75)
        self.label_27.setFont(font6)
        self.label_27.setTextFormat(Qt.PlainText)
        self.label_27.setAlignment(Qt.AlignCenter)
        self.lcdNumber_3 = QLCDNumber(self.centralwidget)
        self.lcdNumber_3.setObjectName(u"lcdNumber_3")
        self.lcdNumber_3.setGeometry(QRect(720, 490, 51, 21))
        self.lcdNumber_3.setFrameShadow(QFrame.Sunken)
        self.lcdNumber_3.setLineWidth(1)
        self.lcdNumber_3.setSegmentStyle(QLCDNumber.Flat)
        self.lcdNumber_4 = QLCDNumber(self.centralwidget)
        self.lcdNumber_4.setObjectName(u"lcdNumber_4")
        self.lcdNumber_4.setGeometry(QRect(650, 490, 71, 21))
        self.lcdNumber_4.setFont(font4)
        self.lcdNumber_4.setSmallDecimalPoint(False)
        self.lcdNumber_4.setDigitCount(6)
        self.lcdNumber_4.setSegmentStyle(QLCDNumber.Flat)
        self.lcdNumber_4.setProperty("value", 123.000000000000000)
        self.lcdNumber_4.setProperty("intValue", 123)
        self.lcdNumber_5 = QLCDNumber(self.centralwidget)
        self.lcdNumber_5.setObjectName(u"lcdNumber_5")
        self.lcdNumber_5.setGeometry(QRect(770, 490, 41, 21))
        self.lcdNumber_5.setFrameShadow(QFrame.Sunken)
        self.lcdNumber_5.setLineWidth(1)
        self.lcdNumber_5.setDigitCount(2)
        self.lcdNumber_5.setSegmentStyle(QLCDNumber.Flat)
        self.checkBox = QCheckBox(self.centralwidget)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(670, 390, 91, 41))
        font7 = QFont()
        font7.setFamily(u"Arial")
        font7.setPointSize(16)
        self.checkBox.setFont(font7)
        self.dial_21 = QDial(self.centralwidget)
        self.dial_21.setObjectName(u"dial_21")
        self.dial_21.setGeometry(QRect(840, 420, 50, 64))
        self.dial_21.setMaximum(20)
        self.dial_21.setValue(3)
        self.lcdNumber_6 = QLCDNumber(self.centralwidget)
        self.lcdNumber_6.setObjectName(u"lcdNumber_6")
        self.lcdNumber_6.setGeometry(QRect(840, 490, 41, 21))
        self.lcdNumber_6.setFrameShadow(QFrame.Sunken)
        self.lcdNumber_6.setLineWidth(1)
        self.lcdNumber_6.setDigitCount(2)
        self.lcdNumber_6.setSegmentStyle(QLCDNumber.Flat)
        self.lcdNumber_6.setProperty("value", 3.000000000000000)
        self.dial_22 = QDial(self.centralwidget)
        self.dial_22.setObjectName(u"dial_22")
        self.dial_22.setGeometry(QRect(940, 420, 50, 64))
        self.dial_22.setMinimum(-10)
        self.dial_22.setMaximum(10)
        self.lcdNumber_7 = QLCDNumber(self.centralwidget)
        self.lcdNumber_7.setObjectName(u"lcdNumber_7")
        self.lcdNumber_7.setGeometry(QRect(940, 490, 41, 21))
        self.lcdNumber_7.setFrameShadow(QFrame.Sunken)
        self.lcdNumber_7.setLineWidth(1)
        self.lcdNumber_7.setDigitCount(2)
        self.lcdNumber_7.setSegmentStyle(QLCDNumber.Flat)
        self.lcdNumber_7.setProperty("intValue", 0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.pushButton.raise_()
        self.graphicsView.raise_()
        self.graphicsView_2.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.tabWidget.raise_()
        self.layoutWidget.raise_()
        self.pushButton_2.raise_()
        self.label_27.raise_()
        self.lcdNumber_3.raise_()
        self.lcdNumber_4.raise_()
        self.lcdNumber_5.raise_()
        self.tabWidget_2.raise_()
        self.checkBox.raise_()
        self.dial_21.raise_()
        self.lcdNumber_6.raise_()
        self.dial_22.raise_()
        self.lcdNumber_7.raise_()
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1017, 23))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.pushButton.setDefault(False)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.pushButton_2.setDefault(False)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"\u542f\u52a8", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\u8282\u70b9A\u753b\u9762", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\u8282\u70b9B\u753b\u9762", None))
        self.radioButton.setText(QCoreApplication.translate("MainWindow", u"\u5173\u95ed", None))
        self.radioButton_2.setText(QCoreApplication.translate("MainWindow", u"\u539f\u59cb", None))
        self.radioButton_3.setText(QCoreApplication.translate("MainWindow", u"after 1", None))
        self.radioButton_4.setText(QCoreApplication.translate("MainWindow", u"after 2", None))
        self.radioButton_9.setText(QCoreApplication.translate("MainWindow", u"\u5dee\u5206", None))
        self.radioButton_10.setText(QCoreApplication.translate("MainWindow", u"\u9608\u503c", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"\u6355\u6349\u8bbe\u5b9a", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\u4e8c\u503c\u5316\u9608\u503c", None))
        self.plainTextEdit.setPlainText(QCoreApplication.translate("MainWindow", u"30", None))
        self.plainTextEdit_2.setPlainText(QCoreApplication.translate("MainWindow", u"1", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"\u6a21\u7cca\u6838\u5927\u5c0f", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"\u53c2\u6570\u8c03\u8282", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"\u6700\u5c0fX\u504f\u79fb", None))
        self.plainTextEdit_3.setPlainText(QCoreApplication.translate("MainWindow", u"1", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"\u6700\u5c0fY\u504f\u79fb", None))
        self.plainTextEdit_4.setPlainText(QCoreApplication.translate("MainWindow", u"1", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"\u6700\u5c0f\u5bbd\u5ea6", None))
        self.plainTextEdit_5.setPlainText(QCoreApplication.translate("MainWindow", u"1", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"\u6700\u5c0f\u9ad8\u5ea6", None))
        self.plainTextEdit_6.setPlainText(QCoreApplication.translate("MainWindow", u"1", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QCoreApplication.translate("MainWindow", u"\u9608\u503cMin", None))
        self.plainTextEdit_10.setPlainText(QCoreApplication.translate("MainWindow", u"800", None))
        self.plainTextEdit_7.setPlainText(QCoreApplication.translate("MainWindow", u"800", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"\u6700\u5927Y\u504f\u79fb", None))
        self.plainTextEdit_8.setPlainText(QCoreApplication.translate("MainWindow", u"800", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"\u6700\u5927\u5bbd\u5ea6", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"\u6700\u5927X\u504f\u79fb", None))
        self.plainTextEdit_9.setPlainText(QCoreApplication.translate("MainWindow", u"800", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"\u6700\u5927\u9ad8\u5ea6", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QCoreApplication.translate("MainWindow", u"\u9608\u503cMAX", None))
        self.radioButton_5.setText(QCoreApplication.translate("MainWindow", u"\u5173\u95ed", None))
        self.radioButton_6.setText(QCoreApplication.translate("MainWindow", u"\u539f\u59cb", None))
        self.radioButton_7.setText(QCoreApplication.translate("MainWindow", u"after 1", None))
        self.radioButton_8.setText(QCoreApplication.translate("MainWindow", u"after 2", None))
        self.radioButton_11.setText(QCoreApplication.translate("MainWindow", u"\u5dee\u5206", None))
        self.radioButton_12.setText(QCoreApplication.translate("MainWindow", u"\u9608\u503c", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"\u6355\u6349", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"\u4e8c\u503c\u5316\u9608\u503c", None))
        self.plainTextEdit_11.setPlainText(QCoreApplication.translate("MainWindow", u"30", None))
        self.plainTextEdit_12.setPlainText(QCoreApplication.translate("MainWindow", u"1", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"\u6838\u5927\u5c0f", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"\u53c2\u6570", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"\u6700\u5c0fX\u504f\u79fb", None))
        self.plainTextEdit_13.setPlainText(QCoreApplication.translate("MainWindow", u"1", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"\u6700\u5c0fY\u504f\u79fb", None))
        self.plainTextEdit_14.setPlainText(QCoreApplication.translate("MainWindow", u"1", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"\u6700\u5c0f\u5bbd\u5ea6", None))
        self.plainTextEdit_15.setPlainText(QCoreApplication.translate("MainWindow", u"1", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"\u6700\u5c0f\u9ad8\u5ea6", None))
        self.plainTextEdit_16.setPlainText(QCoreApplication.translate("MainWindow", u"1", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), QCoreApplication.translate("MainWindow", u"\u9608\u503cMin", None))
        self.plainTextEdit_17.setPlainText(QCoreApplication.translate("MainWindow", u"800", None))
        self.plainTextEdit_18.setPlainText(QCoreApplication.translate("MainWindow", u"800", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"\u6700\u5927Y\u504f\u79fb", None))
        self.plainTextEdit_19.setPlainText(QCoreApplication.translate("MainWindow", u"800", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"\u6700\u5927\u5bbd\u5ea6", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"\u6700\u5927X\u504f\u79fb", None))
        self.plainTextEdit_20.setPlainText(QCoreApplication.translate("MainWindow", u"800", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"\u6700\u5927\u9ad8\u5ea6", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), QCoreApplication.translate("MainWindow", u"\u9608\u503cMAX", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u7ebf\u957fL:", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u89d2\u5ea6\u03b8:", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"cm", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"\u590d\u4f4d", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"Waiting...", None))
        self.checkBox.setText(QCoreApplication.translate("MainWindow", u"\u6d4b\u89d2\u5ea6", None))
    # retranslateUi

